perf: ⚡️ ursa restart when unhealthy (#416)
* refactor: 💡 docker stack health-check

* refactor: 💡 remove prop

* refactor: 💡 restart ursa service when unhealthy

* refactor: 💡 test config file location

* refactor: 💡 small amends, remove line breaks

diff --git a/docker/full-node/docker-compose.yml b/docker/full-node/docker-compose.yml
--- a/docker/full-node/docker-compose.yml
+++ b/docker/full-node/docker-compose.yml
@@ -96,7 +96,7 @@ services:
     build:
       context: ../../.
       dockerfile: Dockerfile
-    restart: on-failure
+    restart: always
     ports:
       - "6009:6009"
     expose:
@@ -107,7 +107,24 @@ services:
     volumes:
       - ${HOME}/.ursa/:/root/.ursa/:rw
     healthcheck:
-      test: ["CMD", "curl", "-f", "http://localhost:4069/ping"]
+      test: |
+        curl http://localhost:4069/ping || (
+          config_path=./docker/full-node/docker-compose.yml
+
+          if [[ ! -f "$config_path" && -f "docker-compose.yml" ]]; then
+            printf "%s\n" "🤖 Found docker-compose.yml in current work dir and will override the default path."
+
+            config_path="docker-compose.yml"
+          fi
+
+          if [[ ! -f "$config_path" ]]; then
+            printf "%s\n" "👹 Oops! The Ursa service should be restarted but we couldn't locate the Stack configuration file. Have you started the Stack from the project root?"
+
+            exit 1
+          fi
+
+          docker-compose -f "$config_path" restart ursa
+        )
       interval: 5m
       timeout: 10s
       retries: 3
